//go:build integration && oracle

package db_test

import (
	"bytes"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/godror/godror"
	"github.com/zhuhanxin0308/thinkgo/framework/db"
	"github.com/zhuhanxin0308/thinkgo/framework/db/connector"
)

// TestLiveOracleContract 显式启用 Oracle 驱动并使用真实 OCI 客户端验证同一组数据库契约。
func TestLiveOracleContract(t *testing.T) { assertExtendedSQLContract(t, "oracle", "ORACLE") }

// TestLiveOracleBatchDataAndAtomicity 验证批量主键修复保留大字段、空值、时间与跨批次失败原子性。
func TestLiveOracleBatchDataAndAtomicity(t *testing.T) {
	if os.Getenv("THINKGO_LIVE_ORACLE_HOST") == "" {
		t.Skip("未配置独立 Oracle 环境")
	}
	connection, err := (&connector.Oracle{}).Connect(db.Config{
		Type: "oracle", Hostname: os.Getenv("THINKGO_LIVE_ORACLE_HOST"),
		Hostport: os.Getenv("THINKGO_LIVE_ORACLE_PORT"), Database: os.Getenv("THINKGO_LIVE_ORACLE_DATABASE"),
		Username: os.Getenv("THINKGO_LIVE_ORACLE_USER"), Password: os.Getenv("THINKGO_LIVE_ORACLE_PASSWORD"),
		Params: map[string]string{"protocol": "tcp"},
	})
	if err != nil {
		t.Fatal(err)
	}
	database := db.NewDB(connection)
	t.Cleanup(func() {
		if err := database.Close(); err != nil {
			t.Error(err)
		}
	})
	table := liveSQLTableName()
	if _, err := database.Execute("CREATE TABLE " + table + " (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(128) UNIQUE, note CLOB, payload BLOB, created_at TIMESTAMP)"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if _, err := database.Execute("DROP TABLE " + table); err != nil {
			t.Error(err)
		}
	})
	const largeUnits = 8192
	text := strings.Repeat("审计", largeUnits)
	binary := bytes.Repeat([]byte{0, 1, 2, 255}, largeUnits)
	instant := time.Date(2026, time.September, 22, 0, 0, 0, 0, time.UTC)
	rows := make([]map[string]any, 2)
	for index := range rows {
		rows[index] = map[string]any{"name": fmt.Sprintf("large-%d", index), "note": godror.Lob{Reader: strings.NewReader(text), IsClob: true}, "payload": godror.Lob{Reader: bytes.NewReader(binary)}, "created_at": instant}
	}
	if affected, err := database.Table(table).InsertAll(rows); err != nil || affected != int64(len(rows)) {
		t.Fatalf("大字段批量写入: %d %v", affected, err)
	}
	result, err := database.Query("SELECT DBMS_LOB.GETLENGTH(note) AS note_length, DBMS_LOB.GETLENGTH(payload) AS payload_length, created_at FROM " + table + " ORDER BY id")
	if err != nil || len(result) != len(rows) {
		t.Fatalf("读取大字段: %v %v", result, err)
	}
	for _, row := range result {
		textLength, textErr := strconv.ParseInt(fmt.Sprint(row["NOTE_LENGTH"]), 10, 64)
		binaryLength, binaryErr := strconv.ParseInt(fmt.Sprint(row["PAYLOAD_LENGTH"]), 10, 64)
		if textErr != nil || binaryErr != nil || textLength != int64(len([]rune(text))) || binaryLength != int64(len(binary)) {
			t.Fatalf("大字段截断: %v %v %v", row, textErr, binaryErr)
		}
		value, ok := row["CREATED_AT"].(time.Time)
		if !ok || !value.Equal(instant) {
			t.Fatalf("时间往返错误: %v", row)
		}
	}
	if affected, err := database.Table(table).InsertAll([]map[string]any{
		{"name": "nullable-1", "note": nil, "payload": nil, "created_at": nil},
		{"name": "nullable-2", "note": nil, "payload": nil, "created_at": nil},
	}); err != nil || affected != 2 {
		t.Fatalf("空值批量写入: %d %v", affected, err)
	}
	if affected, err := database.Table(table).InsertAll([]map[string]any{
		{"name": "mixed-null", "note": nil, "payload": nil, "created_at": nil},
		{"name": "mixed-lob", "note": godror.Lob{Reader: strings.NewReader(text), IsClob: true}, "payload": godror.Lob{Reader: bytes.NewReader(binary)}, "created_at": instant},
	}); err != nil || affected != 2 {
		t.Fatalf("空值与大字段混合写入: %d %v", affected, err)
	}
	if affected, err := database.Table(table).InsertAll([]map[string]any{
		{"name": 1001, "note": nil, "payload": nil, "created_at": nil},
		{"name": "1002", "note": nil, "payload": nil, "created_at": nil},
	}); err != nil || affected != 2 {
		t.Fatalf("目标列合法的混合绑定类型被拒绝: %d %v", affected, err)
	}
	const rollbackRows = 400
	failing := make([]map[string]any, rollbackRows)
	for index := range failing {
		failing[index] = map[string]any{"name": fmt.Sprintf("rollback-%d", index), "note": nil, "payload": nil, "created_at": nil}
	}
	failing[len(failing)-1]["name"] = "large-0"
	if affected, err := database.Table(table).InsertAll(failing); err == nil || affected != 0 {
		t.Fatalf("重复键没有使跨批次写入失败: %d %v", affected, err)
	}
	if count, err := database.Table(table).Count(); err != nil || count != 8 {
		t.Fatalf("跨批次失败残留部分写入: %d %v", count, err)
	}
}
