//go:build integration

package db_test

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/zhuhanxin0308/thinkgo/framework/db"
	"github.com/zhuhanxin0308/thinkgo/framework/db/connector"
)

// TestLiveSQLServerContract 将 SQL Server 的真实执行结果与现有查询、批量、事务和取消契约核对。
func TestLiveSQLServerContract(t *testing.T) { assertExtendedSQLContract(t, "sqlsrv", "SQLSERVER") }

func assertExtendedSQLContract(t *testing.T, driver, environment string) {
	t.Helper()
	prefix := "THINKGO_LIVE_" + environment + "_"
	if os.Getenv(prefix+"HOST") == "" {
		t.Skip("未配置独立数据库环境")
	}
	connector.RegisterBuiltins()
	databaseConnector, err := db.GetConnector(driver)
	if err != nil {
		t.Fatal(err)
	}
	params := map[string]string{"encrypt": "true", "TrustServerCertificate": "true"}
	if driver == "oracle" {
		params = map[string]string{"protocol": "tcp"}
	}
	connection, err := databaseConnector.Connect(db.Config{
		Type: driver, Hostname: os.Getenv(prefix + "HOST"), Hostport: os.Getenv(prefix + "PORT"),
		Database: os.Getenv(prefix + "DATABASE"), Username: os.Getenv(prefix + "USER"), Password: os.Getenv(prefix + "PASSWORD"),
		Params: params, MaxOpenConns: 4, MaxIdleConns: 2,
	})
	if err != nil {
		t.Fatal(err)
	}
	database := db.NewDB(connection)
	t.Cleanup(func() {
		if err := database.Close(); err != nil {
			t.Error(err)
		}
	})
	table := liveSQLTableName()
	schema := "CREATE TABLE %s (id BIGINT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(128) NOT NULL, score INT NOT NULL)"
	if driver == "oracle" {
		schema = "CREATE TABLE %s (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name NVARCHAR2(128) NOT NULL, score NUMBER(10) NOT NULL)"
	}
	if _, err := database.Execute(fmt.Sprintf(schema, table)); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if _, err := database.Execute("DROP TABLE " + table); err != nil {
			t.Error(err)
		}
	})
	value := func(row map[string]any, key string) any {
		for name, value := range row {
			if strings.EqualFold(name, key) {
				return value
			}
		}
		return nil
	}
	id, err := database.Table(table).InsertGetId(map[string]any{"name": "审计 Alice", "score": 10})
	if err != nil {
		t.Fatalf("回传主键: %v", err)
	}
	identifier, err := liveSQLInt64(id)
	if err != nil || identifier < 1 {
		t.Fatalf("主键非法: %v %v", id, err)
	}
	row, err := database.Table(table).WhereField("id", "=", identifier).Find()
	if err != nil || liveSQLText(value(row, "name")) != "审计 Alice" {
		t.Fatalf("Unicode 往返: %v %v", row, err)
	}
	if affected, err := database.Table(table).InsertAll([]map[string]any{{"name": "Bob", "score": 20}, {"name": "Carol", "score": 30}}); err != nil || affected != 2 {
		t.Fatalf("批量写入: %d %v", affected, err)
	}
	rows, err := database.Table(table).Order("id ASC").Limit(1).Offset(1).Select()
	if err != nil || len(rows) != 1 || liveSQLText(value(rows[0], "name")) != "Bob" {
		t.Fatalf("分页: %v %v", rows, err)
	}
	if affected, err := database.Table(table).WhereField("id", "=", identifier).Update(map[string]any{"score": 11}); err != nil || affected != 1 {
		t.Fatalf("更新: %d %v", affected, err)
	}
	if count, err := database.Table(table).WhereField("name", "=", "' OR 1=1 --").Count(); err != nil || count != 0 {
		t.Fatalf("参数值被解释为 SQL: %d %v", count, err)
	}
	rollback := errors.New("审计主动回滚")
	err = database.Transaction(func(tx *db.Tx) error {
		if _, err := tx.Table(table).Insert(map[string]any{"name": "rollback", "score": 40}); err != nil {
			return err
		}
		return rollback
	})
	if !errors.Is(err, rollback) {
		t.Fatalf("事务错误丢失: %v", err)
	}
	if count, err := database.Table(table).WhereField("name", "=", "rollback").Count(); err != nil || count != 0 {
		t.Fatalf("回滚副作用: %d %v", count, err)
	}
	err = database.Transaction(func(tx *db.Tx) error {
		_, err := tx.Table(table).Insert(map[string]any{"name": "commit", "score": 50})
		return err
	})
	if err != nil {
		t.Fatalf("提交: %v", err)
	}
	var streamed int
	if err := database.Table(table).Order("id ASC").Each(func(row map[string]any) bool { streamed++; return value(row, "name") != nil }); err != nil || streamed != 4 {
		t.Fatalf("流式行数: %d %v", streamed, err)
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	started := time.Now()
	if _, err := database.Table(table).WithContext(ctx).Select(); !errors.Is(err, context.Canceled) || time.Since(started) > time.Second {
		t.Fatalf("取消未传播: %v", err)
	}
	if affected, err := database.Table(table).WhereField("id", "=", identifier).Delete(); err != nil || affected != 1 {
		t.Fatalf("删除: %d %v", affected, err)
	}
	if count, err := database.Table(table).Count(); err != nil || count != 3 {
		t.Fatalf("最终状态: %d %v", count, err)
	}
}
